### ISSUE TITLE
Would you consider packaging release here on GH?

### ISSUE THREAD

**Issue by schwim0341** [TheGeneticsGuy/Guild-Roster-Manager---Group-Info#3]
Hello there!

For those of us using a third party addon manager that can no longer install your addon due to the Curse API change, would you consider posting releases with the zip file so we can install from URL and purge the Curse link?

Thanks for your consideration!

**Comment by JVemmer** [comment]
It's available from wago.io here: [https://addons.wago.io/addons/guild-roster-manager](https://addons.wago.io/addons/guild-roster-manager) - The name is slightly different from Curse, so WowUp will not display it as the same addon; I recommend deleting the Curse version and getting the wago.io version.

**Comment by TheGeneticsGuy** [comment]
I completely forgot this addon existed I wrote for GRM lol - I'll get it updated and on Wago.

**Comment by TheGeneticsGuy** [comment]
I'll package a release on github too, it's pretty simple. I hear some addon managers look for that

**Comment by TheGeneticsGuy** [comment]
GRM is now release packaged on github - I will work on updating this module above as I kind of forgot it exists lol
