### ISSUE TITLE
GRM Issue when opening main GRM settings window

### ISSUE THREAD

**Issue by Teng3n** [TheGeneticsGuy/Guild-Roster-Manager---Group-Info#4]
> 21x Guild_Roster_Manager\Guild_Roster_Manager-1.9297.lua:6345: attempt to compare nil with number
> [string "@Guild_Roster_Manager\Guild_Roster_Manager-1.9297.lua"]:6345: in function `GetLevelRange'
> [string "@Guild_Roster_Manager\GRM_UI.lua"]:14939: in function `BuildLogFrames'
> [string "@Guild_Roster_Manager\GRM_UI.lua"]:12000: in function <Guild_Roster_Manager\GRM_UI.lua:11999>
> [string "=[C]"]: in function `Show'
> [string "@Guild_Roster_Manager\Guild_Roster_Manager-1.9297.lua"]:3708: in function `DelayMinimapButtonOpen'
> [string "@Guild_Roster_Manager\GRM_UI.lua"]:5104: in function <Guild_Roster_Manager\GRM_UI.lua:5089>
> 
> Locals:
> result = "|cffffd100Reporting:|r|cff00ccff"
> initialNumber = "68-70"
> caps = <table> {
>  1 = 10
>  2 = 20
>  3 = 30
>  4 = 40
>  5 = 50
>  6 = 60
> }
> addon = 60
> atLeastOne = true
> count = 1
> (for index) = 7
> (for limit) = 8
> (for step) = 1
> i = 7
> (*temporary) = 68
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "attempt to compare nil with number"
>

**Comment by TheGeneticsGuy** [comment]
This is now fixed in new build
