### ISSUE TITLE
Managing StoredVariable Size

### ISSUE THREAD

**Issue by shawngmc** [TheGeneticsGuy/Guild-Roster-Manager---Group-Info#5]
Is there any way to manage overall database size?

Currently, my SavedVariables for GRM is over 20MB; It has data from guilds I haven't logged into in years. The overall database format seems... very verbose, even as LUA goes.

Any recommendations on how to clean unnecessary parts of it?

Note: Did not mean to submit the ticket with an empty description, sorry.

**Comment by TheGeneticsGuy** [comment]
That's ok - you can actually delete the old guilds. /grm > Options > Backup > Right click guild and remove it - it is account-wide data so you can delete it all completely.

The vast majority of the data is going to be the guild logs are stored and I do not compress any of the data. But guilds years cna sometimes have tens of thousands of lines of code lol - Myself my addon is like > 100Mb in the saved variable, which is actually smaller than my TSM saved data, but this is how you'd remove the data and permanent trace of the old  guilds.

**Comment by TheGeneticsGuy** [comment]
Just marking resolved for now - Another way is you can always export your logs and save them locally, then delete.
